package database.entities;
// Generated 2016-09-29 20:51:33 by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Diet generated by hbm2java
 */
public class Diet extends Entity {

	private static final long serialVersionUID = -2334508004434775181L;
	private Integer id;
	private User user;
	private String name;
	private Integer dailyRequirement;
	private Integer breakfastCount;
	private Integer mainDishCount;
	private Integer supperCount;
	private Date validFrom;
	private Date validTo;
	private Set<Meal> meals = new HashSet<Meal>(0);

	public Diet(){
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getDailyRequirement() {
		return dailyRequirement;
	}

	public void setDailyRequirement(Integer dailyRequirement) {
		this.dailyRequirement = dailyRequirement;
	}

	public Integer getBreakfastCount() {
		return breakfastCount;
	}

	public void setBreakfastCount(Integer breakfastCount) {
		this.breakfastCount = breakfastCount;
	}

	public Integer getMainDishCount() {
		return mainDishCount;
	}

	public void setMainDishCount(Integer mainDishCount) {
		this.mainDishCount = mainDishCount;
	}

	public Integer getSupperCount() {
		return supperCount;
	}

	public void setSupperCount(Integer supperCount) {
		this.supperCount = supperCount;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Date getValidFrom() {
		return this.validFrom;
	}

	public void setValidFrom(Date validFrom) {
		this.validFrom = validFrom;
	}

	public Date getValidTo() {
		return validTo;
	}

	public void setValidTo(Date validTo) {
		this.validTo = validTo;
	}

	public Set<Meal> getMeals() {
		return this.meals;
	}

	public void setMeals(Set<Meal> dietMeals) {
		this.meals = dietMeals;
	}
 
}
