package database.entities;
// Generated 2016-09-29 20:51:33 by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Diet generated by hbm2java
 */
public class Diet implements java.io.Serializable {

	private Integer id;
	private User user;
	private int mealIds;
	private Date validFrom;
	private Set dietMeals = new HashSet(0);

	public Diet() {
	}

	public Diet(User user, int mealIds, Date validFrom) {
		this.user = user;
		this.mealIds = mealIds;
		this.validFrom = validFrom;
	}

	public Diet(User user, int mealIds, Date validFrom, Set dietMeals) {
		this.user = user;
		this.mealIds = mealIds;
		this.validFrom = validFrom;
		this.dietMeals = dietMeals;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public int getMealIds() {
		return this.mealIds;
	}

	public void setMealIds(int mealIds) {
		this.mealIds = mealIds;
	}

	public Date getValidFrom() {
		return this.validFrom;
	}

	public void setValidFrom(Date validFrom) {
		this.validFrom = validFrom;
	}

	public Set getDietMeals() {
		return this.dietMeals;
	}

	public void setDietMeals(Set dietMeals) {
		this.dietMeals = dietMeals;
	}

}
