package database.entities;
// Generated 2016-11-11 15:44:57 by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Dietday generated by hbm2java
 */
public class Dietday implements java.io.Serializable {

	private Integer id;
	private Diet diet;
	private Date date;
	private Set<Meal> meals = new HashSet<Meal>(0);

	public Dietday() {
	}

	public Dietday(Diet diet, Date date) {
		this.diet = diet;
		this.date = date;
	}

	public Dietday(Diet diet, Date date, Set<Meal> meals) {
		this.diet = diet;
		this.date = date;
		this.meals = meals;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Diet getDiet() {
		return this.diet;
	}

	public void setDiet(Diet diet) {
		this.diet = diet;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public Set<Meal> getMeals() {
		return this.meals;
	}

	public void setMeals(Set<Meal> meals) {
		this.meals = meals;
	}

}
