package database.entities;
// Generated 2016-09-25 00:14:06 by Hibernate Tools 5.2.0.Beta1

/**
 * Exercise generated by hbm2java
 */
public class Exercise implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 337894785721069565L;
	private Integer id;
	private String name;
	private String description;
	private String objective;
	private boolean requiresEquipment;
	private Integer difficultyLevel;
	private String musclesTargeted;

	public Exercise() {
	}

	public Exercise(String name, String objective, boolean requiresEquipment) {
		this.name = name;
		this.objective = objective;
		this.requiresEquipment = requiresEquipment;
	}

	public Exercise(String name, String description, String objective, boolean requiresEquipment,
			Integer difficultyLevel, String musclesTargeted) {
		this.name = name;
		this.description = description;
		this.objective = objective;
		this.requiresEquipment = requiresEquipment;
		this.difficultyLevel = difficultyLevel;
		this.musclesTargeted = musclesTargeted;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getObjective() {
		return this.objective;
	}

	public void setObjective(String objective) {
		this.objective = objective;
	}

	public boolean isRequiresEquipment() {
		return this.requiresEquipment;
	}

	public void setRequiresEquipment(boolean requiresEquipment) {
		this.requiresEquipment = requiresEquipment;
	}

	public Integer getDifficultyLevel() {
		return this.difficultyLevel;
	}

	public void setDifficultyLevel(Integer difficultyLevel) {
		this.difficultyLevel = difficultyLevel;
	}

	public String getMusclesTargeted() {
		return this.musclesTargeted;
	}

	public void setMusclesTargeted(String musclesTargeted) {
		this.musclesTargeted = musclesTargeted;
	}

}
