package database.entities;
// Generated 2016-09-29 16:40:14 by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;

/**
 * Meal generated by hbm2java
 */
public class Meal implements Entity {

	private Integer id;
	private String name;
	private char objective;
	private int gramature;
	private int carbohydratesPercentage;
	private int proteinPercentage;
	private int fatPercentage;
	private Set dietMeals = new HashSet(0);

	public Meal() {
	}

	public Meal(String name, char objective, int gramature, int carbohydratesPercentage, int proteinPercentage,
			int fatPercentage) {
		this.name = name;
		this.objective = objective;
		this.gramature = gramature;
		this.carbohydratesPercentage = carbohydratesPercentage;
		this.proteinPercentage = proteinPercentage;
		this.fatPercentage = fatPercentage;
	}

	public Meal(String name, char objective, int gramature, int carbohydratesPercentage, int proteinPercentage,
			int fatPercentage, Set dietMeals) {
		this.name = name;
		this.objective = objective;
		this.gramature = gramature;
		this.carbohydratesPercentage = carbohydratesPercentage;
		this.proteinPercentage = proteinPercentage;
		this.fatPercentage = fatPercentage;
		this.dietMeals = dietMeals;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public char getObjective() {
		return this.objective;
	}

	public void setObjective(char objective) {
		this.objective = objective;
	}

	public int getGramature() {
		return this.gramature;
	}

	public void setGramature(int gramature) {
		this.gramature = gramature;
	}

	public int getCarbohydratesPercentage() {
		return this.carbohydratesPercentage;
	}

	public void setCarbohydratesPercentage(int carbohydratesPercentage) {
		this.carbohydratesPercentage = carbohydratesPercentage;
	}

	public int getProteinPercentage() {
		return this.proteinPercentage;
	}

	public void setProteinPercentage(int proteinPercentage) {
		this.proteinPercentage = proteinPercentage;
	}

	public int getFatPercentage() {
		return this.fatPercentage;
	}

	public void setFatPercentage(int fatPercentage) {
		this.fatPercentage = fatPercentage;
	}

	public Set getDietMeals() {
		return this.dietMeals;
	}

	public void setDietMeals(Set dietMeals) {
		this.dietMeals = dietMeals;
	}

}
