package database.entities;
// Generated 2016-09-29 16:40:14 by Hibernate Tools 5.2.0.Beta1

/**
 * Shadow generated by hbm2java
 */
public class Shadow implements Entity {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4642354609641232304L;
	private String login;
	private String pass;
	private int userId;
	private User user;

	public Shadow() {
	}
	
	public Shadow(String login, String pass) {
		this.login = login;
		this.pass = pass;
		this.userId = 0;
	}
	
	public Shadow(String login, String pass, int userId) {
		this.login = login;
		this.pass = pass;
		this.userId = userId;
	}

	public Shadow(String login, String pass, int userId, User user) {
		this.login = login;
		this.pass = pass;
		this.userId = userId;
		this.user = user;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getPass() {
		return this.pass;
	}

	public void setPass(String pass) {
		this.pass = pass;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}
	
	public boolean equals(Shadow other){
		if (this.login.equals(other.login) && this.pass.equals(other.pass))
			return true;
		return false;
	}

}
