package database.entities;
// Generated 2016-09-25 00:14:06 by Hibernate Tools 5.2.0.Beta1

import java.util.Date;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private static final long serialVersionUID = -730931351694598868L;
	private Integer id;
	private String name;
	private String surname;
	private Date dateOfBirth;
	private String sex;
	private int height;
	private float weightStart;
	private float weightDesired;
	private Integer fatPercentage;
	private String objective;

	public User() {
	}

	public User(String name, String surname, Date dateOfBirth, String sex, int height, float weightStart,
			float weightDesired) {
		this.name = name;
		this.surname = surname;
		this.dateOfBirth = dateOfBirth;
		this.sex = sex;
		this.height = height;
		this.weightStart = weightStart;
		this.weightDesired = weightDesired;
	}

	public User(String name, String surname, Date dateOfBirth, String sex, int height, float weightStart,
			float weightDesired, Integer fatPercentage, String objective) {
		this.name = name;
		this.surname = surname;
		this.dateOfBirth = dateOfBirth;
		this.sex = sex;
		this.height = height;
		this.weightStart = weightStart;
		this.weightDesired = weightDesired;
		this.fatPercentage = fatPercentage;
		this.objective = objective;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public Date getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setDateOfBirth(Date dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public int getHeight() {
		return this.height;
	}

	public void setHeight(int height) {
		this.height = height;
	}

	public float getWeightStart() {
		return this.weightStart;
	}

	public void setWeightStart(float weightStart) {
		this.weightStart = weightStart;
	}

	public float getWeightDesired() {
		return this.weightDesired;
	}

	public void setWeightDesired(float weightDesired) {
		this.weightDesired = weightDesired;
	}

	public Integer getFatPercentage() {
		return this.fatPercentage;
	}

	public void setFatPercentage(Integer fatPercentage) {
		this.fatPercentage = fatPercentage;
	}

	public String getObjective() {
		return this.objective;
	}

	public void setObjective(String objective) {
		this.objective = objective;
	}

}
