package database.entities;
// Generated 2016-09-29 16:40:14 by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements Entity {

	private int id;
	private Shadow shadow;
	private String name;
	private String surname;
	private Date dateOfBirth;
	private char sex;
	private int height;
	private float startWeight;
	private float goalWeight;
	private Integer fatPercentage;
	private Character userObjective;
	private Set diets = new HashSet(0);
	private Set workouts = new HashSet(0);

	public User() {
	}

	public User(Shadow shadow, String name, String surname, Date dateOfBirth, char sex, int height, float startWeight,
			float goalWeight) {
		this.shadow = shadow;
		this.name = name;
		this.surname = surname;
		this.dateOfBirth = dateOfBirth;
		this.sex = sex;
		this.height = height;
		this.startWeight = startWeight;
		this.goalWeight = goalWeight;
	}
	
	public User(Shadow shadow, String name, String surname, Date dateOfBirth, Character sex, int height, float startWeight,
			float goalWeight, int fatPercentage, Character userObjective) {
		this.shadow = shadow;
		this.name = name;
		this.surname = surname;
		this.dateOfBirth = dateOfBirth;
		this.sex = sex;
		this.height = height;
		this.startWeight = startWeight;
		this.goalWeight = goalWeight;
		this.fatPercentage = fatPercentage;
		this.userObjective = userObjective;
	}

	public User(Shadow shadow, String name, String surname, Date dateOfBirth, char sex, int height, float startWeight,
			float goalWeight, Integer fatPercentage, Character userObjective, Set diets, Set workouts) {
		this.shadow = shadow;
		this.name = name;
		this.surname = surname;
		this.dateOfBirth = dateOfBirth;
		this.sex = sex;
		this.height = height;
		this.startWeight = startWeight;
		this.goalWeight = goalWeight;
		this.fatPercentage = fatPercentage;
		this.userObjective = userObjective;
		this.diets = diets;
		this.workouts = workouts;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Shadow getShadow() {
		return this.shadow;
	}

	public void setShadow(Shadow shadow) {
		this.shadow = shadow;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public Date getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setDateOfBirth(Date dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	public char getSex() {
		return this.sex;
	}

	public void setSex(char sex) {
		this.sex = sex;
	}

	public int getHeight() {
		return this.height;
	}

	public void setHeight(int height) {
		this.height = height;
	}

	public float getStartWeight() {
		return this.startWeight;
	}

	public void setStartWeight(float startWeight) {
		this.startWeight = startWeight;
	}

	public float getGoalWeight() {
		return this.goalWeight;
	}

	public void setGoalWeight(float goalWeight) {
		this.goalWeight = goalWeight;
	}

	public Integer getFatPercentage() {
		return this.fatPercentage;
	}

	public void setFatPercentage(Integer fatPercentage) {
		this.fatPercentage = fatPercentage;
	}

	public Character getUserObjective() {
		return this.userObjective;
	}

	public void setUserObjective(Character userObjective) {
		this.userObjective = userObjective;
	}

	public Set getDiets() {
		return this.diets;
	}

	public void setDiets(Set diets) {
		this.diets = diets;
	}

	public Set getWorkouts() {
		return this.workouts;
	}

	public void setWorkouts(Set workouts) {
		this.workouts = workouts;
	}

}
