package database.entities;
// Generated 2016-09-29 20:51:33 by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.google.common.collect.BiMap;
import com.google.common.collect.HashBiMap;

/**
 * User generated by hbm2java
 */
public class User extends Entity {

	private static final long serialVersionUID = 5379304988252679983L;
	private Integer id;
	private String name;
	private String surname;
	private Date dateOfBirth;
	private char sex;
	private int height;
	private float startWeight;
	private float goalWeight;
	private Integer fatPercentage;
	private Character userObjective;
	private Set diets = new HashSet(0);
	private Shadow shadow;
	private Set workouts = new HashSet(0);
	private static BiMap<Character, String> sexTranslations;
	private static BiMap<Character, String> objectiveTranslations;

	public User() {
		initializeMaps();
	}

	public User(String name, String surname, Date dateOfBirth, char sex, int height, float startWeight,
			float goalWeight) {
		this();
		this.name = name;
		this.surname = surname;
		this.dateOfBirth = dateOfBirth;
		this.sex = sex;
		this.height = height;
		this.startWeight = startWeight;
		this.goalWeight = goalWeight;
	}

	public User(String name, String surname, Date dateOfBirth, char sex, int height, float startWeight,
			float goalWeight, Integer fatPercentage, Character userObjective, Set diets, Shadow shadow, Set workouts) {
		this();
		this.name = name;
		this.surname = surname;
		this.dateOfBirth = dateOfBirth;
		this.sex = sex;
		this.height = height;
		this.startWeight = startWeight;
		this.goalWeight = goalWeight;
		this.fatPercentage = fatPercentage;
		this.userObjective = userObjective;
		this.diets = diets;
		this.shadow = shadow;
		this.workouts = workouts;
	}


	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public Date getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setDateOfBirth(Date dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	public char getSex() {
		return this.sex;
	}
	
	public String getSexString(){
		return parseSexCharToString(sex);
	}
	
	public void setSex(char sex) {
		this.sex = sex;
	}
	
	public void setSexFromString(String sexString) {
		this.sex = parseSexStringToChar(sexString);
	}

	public int getHeight() {
		return this.height;
	}

	public void setHeight(int height) {
		this.height = height;
	}

	public float getStartWeight() {
		return this.startWeight;
	}

	public void setStartWeight(float startWeight) {
		this.startWeight = startWeight;
	}

	public float getGoalWeight() {
		return this.goalWeight;
	}

	public void setGoalWeight(float goalWeight) {
		this.goalWeight = goalWeight;
	}

	public Integer getFatPercentage() {
		return this.fatPercentage;
	}

	public void setFatPercentage(Integer fatPercentage) {
		this.fatPercentage = fatPercentage;
	}

	public Character getUserObjective() {
		return this.userObjective;
	}
	
	public String getUserObjectiveString(){
		return parseUserObjectiveCharToString(userObjective);
	}

	public void setUserObjective(Character userObjective) {
		this.userObjective = userObjective;
	}

	public void setUserObjectiveFromString(String userObjectiveString){
		this.userObjective = parseUserObjectiveStringToChar(userObjectiveString);
	}
	
	public Set getDiets() {
		return this.diets;
	}

	public void setDiets(Set diets) {
		this.diets = diets;
	}

	public Shadow getShadow() {
		return this.shadow;
	}

	public void setShadow(Shadow shadow) {
		this.shadow = shadow;
	}

	public Set getWorkouts() {
		return this.workouts;
	}

	public void setWorkouts(Set workouts) {
		this.workouts = workouts;
	}

	public float calculateBMI(){
		float heightMeters = height / 100f;
		return startWeight / (heightMeters*heightMeters);
	}
	
	private void initializeMaps(){
		sexTranslations = HashBiMap.create();
		sexTranslations.put('m', "Male");
		sexTranslations.put('f', "Female");
		
		objectiveTranslations = HashBiMap.create();
		objectiveTranslations.put('m', "Mass Gain");
		objectiveTranslations.put('r', "Reduction");
		objectiveTranslations.put('s', "Strength");
	}
	
	private String parseUserObjectiveCharToString(Character objectiveChar){
		return objectiveTranslations.getOrDefault(objectiveChar, "Error!");
	}
	
	private Character parseUserObjectiveStringToChar(String objectiveString){
		return objectiveTranslations.inverse().getOrDefault(objectiveString, 'e');
	}
	
	private String parseSexCharToString(Character sexChar){
		return sexTranslations.getOrDefault(sexChar, "Error!");
	}
	
	private Character parseSexStringToChar(String sexString){
		return sexTranslations.inverse().getOrDefault(sexString, 'e');
	}
}
