package database.entities;
// Generated 2016-11-27 13:31:43 by Hibernate Tools 5.2.0.Beta1

/**
 * Weighthistory generated by hbm2java
 */
public class Weighthistory extends Entity {
	private static final long serialVersionUID = 6741631853926639156L;
	private WeighthistoryId id;
	private float weight;

	public Weighthistory() {
	}

	public Weighthistory(WeighthistoryId id, float weight) {
		this.id = id;
		this.weight = weight;
	}

	@Override
	public WeighthistoryId getId() {
		return this.id;
	}

	public void setId(WeighthistoryId id) {
		this.id = id;
	}

	public float getWeight() {
		return this.weight;
	}

	public void setWeight(float weight) {
		this.weight = weight;
	}

}
