package database.entities;
// Generated 2016-11-27 00:30:46 by Hibernate Tools 5.2.0.Beta1

import java.util.Date;

/**
 * Weighthistory generated by hbm2java
 */
public class Weighthistory extends Entity {

	private Integer id;
	private User user;
	private float weight;
	private Date date;

	public Weighthistory() {
	}

	public Weighthistory(User user, float weight, Date date) {
		this.user = user;
		this.weight = weight;
		this.date = date;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public float getWeight() {
		return this.weight;
	}

	public void setWeight(float weight) {
		this.weight = weight;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
