package database.entities;
// Generated 2016-10-30 15:10:58 by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Workout generated by hbm2java
 */
public class Workout implements java.io.Serializable {


	private static final long serialVersionUID = 5479860479872562447L;
	private Integer id;
	private int userId;
	private String name;
	private Date validFrom;
	private Date validTo;
	private Character objective;
	private Set<Workoutday> workoutdays = new HashSet<>(0);

	public Workout(int userId, String name, Date validFrom, Date validTo) {
		this.userId = userId;
		this.name = name;
		this.validFrom = validFrom;
		this.validTo = validTo;
	}

	public Workout(int userId, String name, Date validFrom, Date validTo, Character objective,
			Set<Workoutday> workoutdays) {
		this.userId = userId;
		this.name = name;
		this.validFrom = validFrom;
		this.validTo = validTo;
		this.objective = objective;
		this.workoutdays = workoutdays;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getValidFrom() {
		return this.validFrom;
	}

	public void setValidFrom(Date validFrom) {
		this.validFrom = validFrom;
	}

	public Date getValidTo() {
		return this.validTo;
	}

	public void setValidTo(Date validTo) {
		this.validTo = validTo;
	}

	public Character getObjective() {
		return this.objective;
	}

	public void setObjective(Character objective) {
		this.objective = objective;
	}

	public Set<Workoutday> getWorkoutdays() {
		return this.workoutdays;
	}

	public void setWorkoutdays(Set<Workoutday> workoutdays) {
		this.workoutdays = workoutdays;
	}

}
