package database.entities;
// Generated 2016-09-29 20:51:33 by Hibernate Tools 5.2.0.Beta1

/**
 * WorkoutExerciseId generated by hbm2java
 */
public class WorkoutExerciseId implements java.io.Serializable {

	private int workoutId;
	private int exerciseId;

	public WorkoutExerciseId() {
	}

	public WorkoutExerciseId(int workoutId, int exerciseId) {
		this.workoutId = workoutId;
		this.exerciseId = exerciseId;
	}

	public int getWorkoutId() {
		return this.workoutId;
	}

	public void setWorkoutId(int workoutId) {
		this.workoutId = workoutId;
	}

	public int getExerciseId() {
		return this.exerciseId;
	}

	public void setExerciseId(int exerciseId) {
		this.exerciseId = exerciseId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof WorkoutExerciseId))
			return false;
		WorkoutExerciseId castOther = (WorkoutExerciseId) other;

		return (this.getWorkoutId() == castOther.getWorkoutId()) && (this.getExerciseId() == castOther.getExerciseId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getWorkoutId();
		result = 37 * result + this.getExerciseId();
		return result;
	}

}
